// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_ANIMATIONFLATBUFFER_ANIMATIONFLATBUFFER_H_
#define FLATBUFFERS_GENERATED_ANIMATIONFLATBUFFER_ANIMATIONFLATBUFFER_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

namespace AnimationFlatbuffer {

struct LineFB;

struct TriangleFB;

struct RoundRectFB;

struct RotatedRectFB;

struct CircleFB;

struct AnimationFrameFB;
struct AnimationFrameFBBuilder;

struct AnimationFB;
struct AnimationFBBuilder;

enum PrimitiveFB : uint8_t {
  PrimitiveFB_NONE = 0,
  PrimitiveFB_LineFB = 1,
  PrimitiveFB_TriangleFB = 2,
  PrimitiveFB_RoundRectFB = 3,
  PrimitiveFB_RotatedRectFB = 4,
  PrimitiveFB_CircleFB = 5,
  PrimitiveFB_MIN = PrimitiveFB_NONE,
  PrimitiveFB_MAX = PrimitiveFB_CircleFB
};

inline const PrimitiveFB (&EnumValuesPrimitiveFB())[6] {
  static const PrimitiveFB values[] = {
    PrimitiveFB_NONE,
    PrimitiveFB_LineFB,
    PrimitiveFB_TriangleFB,
    PrimitiveFB_RoundRectFB,
    PrimitiveFB_RotatedRectFB,
    PrimitiveFB_CircleFB
  };
  return values;
}

inline const char * const *EnumNamesPrimitiveFB() {
  static const char * const names[7] = {
    "NONE",
    "LineFB",
    "TriangleFB",
    "RoundRectFB",
    "RotatedRectFB",
    "CircleFB",
    nullptr
  };
  return names;
}

inline const char *EnumNamePrimitiveFB(PrimitiveFB e) {
  if (::flatbuffers::IsOutRange(e, PrimitiveFB_NONE, PrimitiveFB_CircleFB)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesPrimitiveFB()[index];
}

template<typename T> struct PrimitiveFBTraits {
  static const PrimitiveFB enum_value = PrimitiveFB_NONE;
};

template<> struct PrimitiveFBTraits<AnimationFlatbuffer::LineFB> {
  static const PrimitiveFB enum_value = PrimitiveFB_LineFB;
};

template<> struct PrimitiveFBTraits<AnimationFlatbuffer::TriangleFB> {
  static const PrimitiveFB enum_value = PrimitiveFB_TriangleFB;
};

template<> struct PrimitiveFBTraits<AnimationFlatbuffer::RoundRectFB> {
  static const PrimitiveFB enum_value = PrimitiveFB_RoundRectFB;
};

template<> struct PrimitiveFBTraits<AnimationFlatbuffer::RotatedRectFB> {
  static const PrimitiveFB enum_value = PrimitiveFB_RotatedRectFB;
};

template<> struct PrimitiveFBTraits<AnimationFlatbuffer::CircleFB> {
  static const PrimitiveFB enum_value = PrimitiveFB_CircleFB;
};

bool VerifyPrimitiveFB(::flatbuffers::Verifier &verifier, const void *obj, PrimitiveFB type);
bool VerifyPrimitiveFBVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(2) LineFB FLATBUFFERS_FINAL_CLASS {
 private:
  int16_t x0_;
  int16_t y0_;
  int16_t x1_;
  int16_t y1_;
  uint16_t color_;

 public:
  LineFB()
      : x0_(0),
        y0_(0),
        x1_(0),
        y1_(0),
        color_(0) {
  }
  LineFB(int16_t _x0, int16_t _y0, int16_t _x1, int16_t _y1, uint16_t _color)
      : x0_(::flatbuffers::EndianScalar(_x0)),
        y0_(::flatbuffers::EndianScalar(_y0)),
        x1_(::flatbuffers::EndianScalar(_x1)),
        y1_(::flatbuffers::EndianScalar(_y1)),
        color_(::flatbuffers::EndianScalar(_color)) {
  }
  int16_t x0() const {
    return ::flatbuffers::EndianScalar(x0_);
  }
  int16_t y0() const {
    return ::flatbuffers::EndianScalar(y0_);
  }
  int16_t x1() const {
    return ::flatbuffers::EndianScalar(x1_);
  }
  int16_t y1() const {
    return ::flatbuffers::EndianScalar(y1_);
  }
  uint16_t color() const {
    return ::flatbuffers::EndianScalar(color_);
  }
};
FLATBUFFERS_STRUCT_END(LineFB, 10);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(2) TriangleFB FLATBUFFERS_FINAL_CLASS {
 private:
  int16_t x0_;
  int16_t y0_;
  int16_t x1_;
  int16_t y1_;
  int16_t x2_;
  int16_t y2_;
  uint16_t color_;

 public:
  TriangleFB()
      : x0_(0),
        y0_(0),
        x1_(0),
        y1_(0),
        x2_(0),
        y2_(0),
        color_(0) {
  }
  TriangleFB(int16_t _x0, int16_t _y0, int16_t _x1, int16_t _y1, int16_t _x2, int16_t _y2, uint16_t _color)
      : x0_(::flatbuffers::EndianScalar(_x0)),
        y0_(::flatbuffers::EndianScalar(_y0)),
        x1_(::flatbuffers::EndianScalar(_x1)),
        y1_(::flatbuffers::EndianScalar(_y1)),
        x2_(::flatbuffers::EndianScalar(_x2)),
        y2_(::flatbuffers::EndianScalar(_y2)),
        color_(::flatbuffers::EndianScalar(_color)) {
  }
  int16_t x0() const {
    return ::flatbuffers::EndianScalar(x0_);
  }
  int16_t y0() const {
    return ::flatbuffers::EndianScalar(y0_);
  }
  int16_t x1() const {
    return ::flatbuffers::EndianScalar(x1_);
  }
  int16_t y1() const {
    return ::flatbuffers::EndianScalar(y1_);
  }
  int16_t x2() const {
    return ::flatbuffers::EndianScalar(x2_);
  }
  int16_t y2() const {
    return ::flatbuffers::EndianScalar(y2_);
  }
  uint16_t color() const {
    return ::flatbuffers::EndianScalar(color_);
  }
};
FLATBUFFERS_STRUCT_END(TriangleFB, 14);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(2) RoundRectFB FLATBUFFERS_FINAL_CLASS {
 private:
  int16_t x0_;
  int16_t y0_;
  int16_t w_;
  int16_t h_;
  int16_t radius_;
  uint16_t color_;

 public:
  RoundRectFB()
      : x0_(0),
        y0_(0),
        w_(0),
        h_(0),
        radius_(0),
        color_(0) {
  }
  RoundRectFB(int16_t _x0, int16_t _y0, int16_t _w, int16_t _h, int16_t _radius, uint16_t _color)
      : x0_(::flatbuffers::EndianScalar(_x0)),
        y0_(::flatbuffers::EndianScalar(_y0)),
        w_(::flatbuffers::EndianScalar(_w)),
        h_(::flatbuffers::EndianScalar(_h)),
        radius_(::flatbuffers::EndianScalar(_radius)),
        color_(::flatbuffers::EndianScalar(_color)) {
  }
  int16_t x0() const {
    return ::flatbuffers::EndianScalar(x0_);
  }
  int16_t y0() const {
    return ::flatbuffers::EndianScalar(y0_);
  }
  int16_t w() const {
    return ::flatbuffers::EndianScalar(w_);
  }
  int16_t h() const {
    return ::flatbuffers::EndianScalar(h_);
  }
  int16_t radius() const {
    return ::flatbuffers::EndianScalar(radius_);
  }
  uint16_t color() const {
    return ::flatbuffers::EndianScalar(color_);
  }
};
FLATBUFFERS_STRUCT_END(RoundRectFB, 12);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(2) RotatedRectFB FLATBUFFERS_FINAL_CLASS {
 private:
  int16_t x0_;
  int16_t y0_;
  int16_t w_;
  int16_t h_;
  int16_t angle_deg_;
  uint16_t color_;

 public:
  RotatedRectFB()
      : x0_(0),
        y0_(0),
        w_(0),
        h_(0),
        angle_deg_(0),
        color_(0) {
  }
  RotatedRectFB(int16_t _x0, int16_t _y0, int16_t _w, int16_t _h, int16_t _angle_deg, uint16_t _color)
      : x0_(::flatbuffers::EndianScalar(_x0)),
        y0_(::flatbuffers::EndianScalar(_y0)),
        w_(::flatbuffers::EndianScalar(_w)),
        h_(::flatbuffers::EndianScalar(_h)),
        angle_deg_(::flatbuffers::EndianScalar(_angle_deg)),
        color_(::flatbuffers::EndianScalar(_color)) {
  }
  int16_t x0() const {
    return ::flatbuffers::EndianScalar(x0_);
  }
  int16_t y0() const {
    return ::flatbuffers::EndianScalar(y0_);
  }
  int16_t w() const {
    return ::flatbuffers::EndianScalar(w_);
  }
  int16_t h() const {
    return ::flatbuffers::EndianScalar(h_);
  }
  int16_t angle_deg() const {
    return ::flatbuffers::EndianScalar(angle_deg_);
  }
  uint16_t color() const {
    return ::flatbuffers::EndianScalar(color_);
  }
};
FLATBUFFERS_STRUCT_END(RotatedRectFB, 12);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(2) CircleFB FLATBUFFERS_FINAL_CLASS {
 private:
  int16_t x0_;
  int16_t y0_;
  int16_t r_;
  uint8_t quadrants_;
  int8_t padding0__;
  uint16_t color_;

 public:
  CircleFB()
      : x0_(0),
        y0_(0),
        r_(0),
        quadrants_(0),
        padding0__(0),
        color_(0) {
    (void)padding0__;
  }
  CircleFB(int16_t _x0, int16_t _y0, int16_t _r, uint8_t _quadrants, uint16_t _color)
      : x0_(::flatbuffers::EndianScalar(_x0)),
        y0_(::flatbuffers::EndianScalar(_y0)),
        r_(::flatbuffers::EndianScalar(_r)),
        quadrants_(::flatbuffers::EndianScalar(_quadrants)),
        padding0__(0),
        color_(::flatbuffers::EndianScalar(_color)) {
    (void)padding0__;
  }
  int16_t x0() const {
    return ::flatbuffers::EndianScalar(x0_);
  }
  int16_t y0() const {
    return ::flatbuffers::EndianScalar(y0_);
  }
  int16_t r() const {
    return ::flatbuffers::EndianScalar(r_);
  }
  uint8_t quadrants() const {
    return ::flatbuffers::EndianScalar(quadrants_);
  }
  uint16_t color() const {
    return ::flatbuffers::EndianScalar(color_);
  }
};
FLATBUFFERS_STRUCT_END(CircleFB, 10);

struct AnimationFrameFB FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef AnimationFrameFBBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_X0 = 4,
    VT_Y0 = 6,
    VT_DURATION = 8,
    VT_FILL_COLOR = 10,
    VT_PRIMITIVES_TYPE = 12,
    VT_PRIMITIVES = 14
  };
  int16_t x0() const {
    return GetField<int16_t>(VT_X0, 0);
  }
  int16_t y0() const {
    return GetField<int16_t>(VT_Y0, 0);
  }
  uint32_t duration() const {
    return GetField<uint32_t>(VT_DURATION, 0);
  }
  uint16_t fill_color() const {
    return GetField<uint16_t>(VT_FILL_COLOR, 0);
  }
  const ::flatbuffers::Vector<uint8_t> *primitives_type() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_PRIMITIVES_TYPE);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *primitives() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *>(VT_PRIMITIVES);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int16_t>(verifier, VT_X0, 2) &&
           VerifyField<int16_t>(verifier, VT_Y0, 2) &&
           VerifyField<uint32_t>(verifier, VT_DURATION, 4) &&
           VerifyField<uint16_t>(verifier, VT_FILL_COLOR, 2) &&
           VerifyOffset(verifier, VT_PRIMITIVES_TYPE) &&
           verifier.VerifyVector(primitives_type()) &&
           VerifyOffset(verifier, VT_PRIMITIVES) &&
           verifier.VerifyVector(primitives()) &&
           VerifyPrimitiveFBVector(verifier, primitives(), primitives_type()) &&
           verifier.EndTable();
  }
};

struct AnimationFrameFBBuilder {
  typedef AnimationFrameFB Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_x0(int16_t x0) {
    fbb_.AddElement<int16_t>(AnimationFrameFB::VT_X0, x0, 0);
  }
  void add_y0(int16_t y0) {
    fbb_.AddElement<int16_t>(AnimationFrameFB::VT_Y0, y0, 0);
  }
  void add_duration(uint32_t duration) {
    fbb_.AddElement<uint32_t>(AnimationFrameFB::VT_DURATION, duration, 0);
  }
  void add_fill_color(uint16_t fill_color) {
    fbb_.AddElement<uint16_t>(AnimationFrameFB::VT_FILL_COLOR, fill_color, 0);
  }
  void add_primitives_type(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> primitives_type) {
    fbb_.AddOffset(AnimationFrameFB::VT_PRIMITIVES_TYPE, primitives_type);
  }
  void add_primitives(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<void>>> primitives) {
    fbb_.AddOffset(AnimationFrameFB::VT_PRIMITIVES, primitives);
  }
  explicit AnimationFrameFBBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<AnimationFrameFB> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<AnimationFrameFB>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<AnimationFrameFB> CreateAnimationFrameFB(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int16_t x0 = 0,
    int16_t y0 = 0,
    uint32_t duration = 0,
    uint16_t fill_color = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> primitives_type = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<void>>> primitives = 0) {
  AnimationFrameFBBuilder builder_(_fbb);
  builder_.add_primitives(primitives);
  builder_.add_primitives_type(primitives_type);
  builder_.add_duration(duration);
  builder_.add_fill_color(fill_color);
  builder_.add_y0(y0);
  builder_.add_x0(x0);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<AnimationFrameFB> CreateAnimationFrameFBDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int16_t x0 = 0,
    int16_t y0 = 0,
    uint32_t duration = 0,
    uint16_t fill_color = 0,
    const std::vector<uint8_t> *primitives_type = nullptr,
    const std::vector<::flatbuffers::Offset<void>> *primitives = nullptr) {
  auto primitives_type__ = primitives_type ? _fbb.CreateVector<uint8_t>(*primitives_type) : 0;
  auto primitives__ = primitives ? _fbb.CreateVector<::flatbuffers::Offset<void>>(*primitives) : 0;
  return AnimationFlatbuffer::CreateAnimationFrameFB(
      _fbb,
      x0,
      y0,
      duration,
      fill_color,
      primitives_type__,
      primitives__);
}

struct AnimationFB FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef AnimationFBBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_X0 = 4,
    VT_Y0 = 6,
    VT_FRAMES = 8
  };
  int16_t x0() const {
    return GetField<int16_t>(VT_X0, 0);
  }
  int16_t y0() const {
    return GetField<int16_t>(VT_Y0, 0);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<AnimationFlatbuffer::AnimationFrameFB>> *frames() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<AnimationFlatbuffer::AnimationFrameFB>> *>(VT_FRAMES);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int16_t>(verifier, VT_X0, 2) &&
           VerifyField<int16_t>(verifier, VT_Y0, 2) &&
           VerifyOffset(verifier, VT_FRAMES) &&
           verifier.VerifyVector(frames()) &&
           verifier.VerifyVectorOfTables(frames()) &&
           verifier.EndTable();
  }
};

struct AnimationFBBuilder {
  typedef AnimationFB Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_x0(int16_t x0) {
    fbb_.AddElement<int16_t>(AnimationFB::VT_X0, x0, 0);
  }
  void add_y0(int16_t y0) {
    fbb_.AddElement<int16_t>(AnimationFB::VT_Y0, y0, 0);
  }
  void add_frames(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<AnimationFlatbuffer::AnimationFrameFB>>> frames) {
    fbb_.AddOffset(AnimationFB::VT_FRAMES, frames);
  }
  explicit AnimationFBBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<AnimationFB> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<AnimationFB>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<AnimationFB> CreateAnimationFB(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int16_t x0 = 0,
    int16_t y0 = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<AnimationFlatbuffer::AnimationFrameFB>>> frames = 0) {
  AnimationFBBuilder builder_(_fbb);
  builder_.add_frames(frames);
  builder_.add_y0(y0);
  builder_.add_x0(x0);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<AnimationFB> CreateAnimationFBDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int16_t x0 = 0,
    int16_t y0 = 0,
    const std::vector<::flatbuffers::Offset<AnimationFlatbuffer::AnimationFrameFB>> *frames = nullptr) {
  auto frames__ = frames ? _fbb.CreateVector<::flatbuffers::Offset<AnimationFlatbuffer::AnimationFrameFB>>(*frames) : 0;
  return AnimationFlatbuffer::CreateAnimationFB(
      _fbb,
      x0,
      y0,
      frames__);
}

inline bool VerifyPrimitiveFB(::flatbuffers::Verifier &verifier, const void *obj, PrimitiveFB type) {
  switch (type) {
    case PrimitiveFB_NONE: {
      return true;
    }
    case PrimitiveFB_LineFB: {
      return verifier.VerifyField<AnimationFlatbuffer::LineFB>(static_cast<const uint8_t *>(obj), 0, 2);
    }
    case PrimitiveFB_TriangleFB: {
      return verifier.VerifyField<AnimationFlatbuffer::TriangleFB>(static_cast<const uint8_t *>(obj), 0, 2);
    }
    case PrimitiveFB_RoundRectFB: {
      return verifier.VerifyField<AnimationFlatbuffer::RoundRectFB>(static_cast<const uint8_t *>(obj), 0, 2);
    }
    case PrimitiveFB_RotatedRectFB: {
      return verifier.VerifyField<AnimationFlatbuffer::RotatedRectFB>(static_cast<const uint8_t *>(obj), 0, 2);
    }
    case PrimitiveFB_CircleFB: {
      return verifier.VerifyField<AnimationFlatbuffer::CircleFB>(static_cast<const uint8_t *>(obj), 0, 2);
    }
    default: return true;
  }
}

inline bool VerifyPrimitiveFBVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (::flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyPrimitiveFB(
        verifier,  values->Get(i), types->GetEnum<PrimitiveFB>(i))) {
      return false;
    }
  }
  return true;
}

inline const AnimationFlatbuffer::AnimationFB *GetAnimationFB(const void *buf) {
  return ::flatbuffers::GetRoot<AnimationFlatbuffer::AnimationFB>(buf);
}

inline const AnimationFlatbuffer::AnimationFB *GetSizePrefixedAnimationFB(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<AnimationFlatbuffer::AnimationFB>(buf);
}

inline bool VerifyAnimationFBBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<AnimationFlatbuffer::AnimationFB>(nullptr);
}

inline bool VerifySizePrefixedAnimationFBBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<AnimationFlatbuffer::AnimationFB>(nullptr);
}

inline void FinishAnimationFBBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<AnimationFlatbuffer::AnimationFB> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedAnimationFBBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<AnimationFlatbuffer::AnimationFB> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace AnimationFlatbuffer

#endif  // FLATBUFFERS_GENERATED_ANIMATIONFLATBUFFER_ANIMATIONFLATBUFFER_H_
